###For quantification###
#samples
samples: config/samples.tsv
units: config/units.tsv

#kraken db
dbtype: "--standard"

#paired end information
paired: False

###For benchmarking###
benchmarking: False

#Set the number of samples to be generated
number_of_samples: 1

#Reference genomes 
bacteria: config/bacteria.tsv

#number of reads to be fractionated
p: [1000, 5000, 10000, 15000]

#Art: parameters for short read simulation
short_read_len: 150
n_reads_per_seq: 2000 #could be configurable

#Nanosim: parameters for long read simulation
long_nreads: 50000

#Sourmash config
sourmash_scale: 2000

#sourmash db_k21
sourmash_lca_link_k21: "https://osf.io/gk2za/download"
sourmash_lca_name_k21: "gtdb-rs202.genomic.k21.lca.json"

#sourmash db_k51
sourmash_lca_link_k51: "https://osf.io/297dp/download"
sourmash_lca_name_k51: "gtdb-rs202.genomic.k51.lca.json"



