###For quantification
#samples
samples: config/samples.tsv
units: config/units.tsv

#kraken db
#dbtype: "--standard"
dbtype: "--download-library protozoa" #for testing purposes only

#sourmash db_k21
sourmash_lca_link_k21: "https://osf.io/hm3c4/download"
sourmash_lca_name_k21: "gtdb-rs202.genomic.k21.lca.json"

#sourmash db_k51
sourmash_lca_link_k51: "https://osf.io/3cdp6/download"
sourmash_lca_name_k51: "gtdb-rs202.genomic.k51.lca.json"

###For benchmarking
benchmarking: True

#Set the number of samples to be generated
number_of_samples: 1

#Reference genomes 
bacteria: config/bacteria.tsv

#number of reads to be fractionated
p: [1000, 5000, 10000, 15000]

#parameters for short read simulation (fold_coverage required for art settings)
short_read_len: 150
fold_coverage: 10 

#parameters for long read simulation (around 20000 reads)
long_nreads: 50000
med_long_read_len:
min_long_read_len: 300
max_long_read_len: 1000
model_fit: "" #should not be blank for test config, but should be blank here.
#info about e_coli read: check: info.txt

#additional
sourmash_scale: 2000



