#samples
fastq: "config/samples.tsv"

#Set the number of samples to be generated
number_of_samples: 1

#Reference genomes 
#bac_ref: ["GCF_000006765.1_ASM676v1", "GCF_000006945.2_ASM694v2", "GCF_000008565.1_ASM856v1", "GCF_000010365.1_ASM1036v1", "GCF_000012685.1_ASM1268v1", "GCF_000222975.1_ASM22297v1", "merged_GCF_000622225.1_ASM62222v1"]
bacteria: "config/bacteria.tsv"

#number of reads to be fractionated
p: [1000, 5000, 10000, 15000]

#parameters for short read simulation (fold_coverage required for art settings)
short_read_len: 150
fold_coverage: 10 

#parameters for long read simulation (around 20000 reads)
long_nreads: 50000
med_long_read_len:
min_long_read_len: 300
max_long_read_len: 1000

#long read simulation resource files
hum_pro: resources/human_NA12878_DNA_FAB49712_guppy #ready to use error profile for human
ecoli_read: resources #e_coli read file, for more info, check: info.txt

#additional
sourmash_scale: 2000



