name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ master ]

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - name: Linting
      - uses: snakemake/snakemake-github-action@v1.18.0
  	  with:
       	    directory: '.test'
            snakefile: 'workflow/Snakefile'
            args: '--lint'
  Testing:	
    runs-on: ubuntu-latest
    steps:   
      - name: Testing
      - uses: snakemake/snakemake-github-action@v1.18.0
          with:
            directory: '.test'
            snakefile: 'workflow/Snakefile'
            args: '--cores 1 --use-conda --conda-cleanup-pkgs cache'
