- uses: snakemake/snakemake-github-action@v1.18.0
  with:
    directory: '.test'
    snakefile: 'workflow/Snakefile'
    args: '--lint'
- uses: snakemake/snakemake-github-action@v1.18.0
  with:
    directory: '.test'
    snakefile: 'workflow/Snakefile'
    args: '--cores 1 --use-conda --conda-cleanup-pkgs cache'

