name: Tests

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Linting
        uses: snakemake/snakemake-github-action@v1.18.0	
        with:
          directory: '.test'
          snakefile: 'workflow/Snakefile'
          args: '--lint'      
      - name: Testing
        uses: snakemake/snakemake-github-action@v1.18.0
        with:
          directory: '.test'
          snakefile: 'workflow/Snakefile'
          args: '--cores 1 --show-failed-logs --use-conda --conda-cleanup-pkgs cache --conda-frontend mamba'
