name: Tests

on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  Linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Lint workflow
        uses: snakemake/snakemake-github-action@v1.22.0	
        with:
          directory: .
          snakefile: workflow/Snakefile
          args: "--lint"
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Checkout submodules
        uses: textbook/git-checkout-submodule-action@2.0.0

      - name: Test workflow 
        uses: snakemake/snakemake-github-action@v1.22.0
        with:
          directory: .test
          snakefile: workflow/Snakefile
          args: "-j 10 --use-conda --show-failed-logs --conda-frontend mamba --conda-cleanup-pkgs cache"
