name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
      - name: snakemake
        uses: snakemake/snakemake-github-action@v1.18.0


